version: "3"

services:
  mariadb:
    container_name: mariadb
    image: inception/mariadb
    build: ./requirements/mariadb
    env_file: .env
    networks:
      - my_network
    volumes:
      - mariadb_volume:/var/lib/mysql
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    image: inception/wordpress
    build: ./requirements/wordpress
    env_file: .env
    depends_on:
      mariadb:
        condition: service_healthy
    networks: 
      - my_network
    volumes:
      - wordpress_volume:/var/www/wordpress
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: inception/nginx
    build: ./requirements/nginx
    env_file: .env
    depends_on:
      - wordpress
    networks:
      - my_network
    volumes:
      - wordpress_volume:/var/www/wordpress
    ports:
      - 443:443
    restart: unless-stopped

networks:
  my_network:

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      device: /home/avancoll/data/database
      type: volume
      o: bind

  wordpress_volume:
    driver: local
    driver_opts:
      device: /home/avancoll/data/wordpress
      type: volume
      o: bind