FROM debian:bullseye

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y php7.4 php7.4-fpm php7.4-mysql curl

RUN mkdir -p /run/php

RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x wp-cli.phar
RUN mv wp-cli.phar /usr/local/bin/wp

COPY ./config/wp-config.sh ./

WORKDIR /var/www/wordpress
RUN wp core download --allow-root
RUN chown -R www-data:www-data /var/www/wordpress

ENTRYPOINT [ "bash", "/wp-config.sh" ]
